package-lock.json
package.json

react-router-dom
react-hook-form
zod
eslint
prettier
axios
tailwind
react-query
react-redux
@reduxjs-toolkit
dotenv
를 설치했습니다

PR: depend/install-libs

---

src/components/layouts/footer.tsx
src/libs/router/adminRouter.tsx

[design:Footer](https://github.com/mobi-projects/mobi-3rd-2-typescript/pull/26/commits/6e5285b1ff91d8defb03b560719205790d344a61)
- footer 디자인 작업 완료했습니다
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: design/Footer

---

package-lock.json
package.json
src/libs/router/adminRouter.tsx
src/libs/router/router.tsx
src/libs/tailwindCss/designToken/color.ts
src/pages/myInfoPage.tsx

[react-icons](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/5444268ca53e6cf49979193b1ae4fdd21aa47ff0)을 추가했습니다.
[design/myPage](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/85315702f91fe3c72420f46f7701d6184e220b30)
- 디자인 토큰 추가
- myInfoPage 퍼블리싱
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR : Design/my page

---

src/components/commons/overlay.tsx

- [feat/overlay 생성](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/e3abbec9c0bdfa0f760005aad47ca3e95a758d1e)
- width 기본값 max-w-4xl
- height 기본값 h-auto
```
// 사용법
const Ex = () => {
const [isOpen,setIsOpen] = useState(false);
const toggleOverlay = () => setIsOpen(!isOpen);
return (
<div>
<button onClick-{toggleOverlay}>클릭</button>
<Overlay isOpen={isOpen} onClose={()=>setIsOpen(false)} widthCss={"max-w-lg"} heightCss={"h-1/2"} >
<p>예시.</p>
</Overlay>
</div>
)
}
```
<br/>
<br/>
<br/>
<br/>
<br/>
1. 아래의 템플릿을 복사 하여, 위의 …

PR : feat/overlay 생성

---

src/components/pokemonDetailPage/pokeEvolution.tsx
src/components/pokemonDetailPage/pokeInfo.tsx
src/libs/router/adminRouter.tsx
src/pages/poketMonDetailPage.tsx
src/pages/signupPage.tsx

- [design/pokemonDetailPage 생성](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/ec1de00646627dc98f3ad6df9906364)
- Overlay 테스트가 아직 완료되지 않음
- pokemon card가 완성되면 추가되어야함
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR : design/pokemonDetailPage

---

src/libs/axios/axiosInstance.ts
src/libs/axios/userAPI.ts

[feat:userApi 생성완료](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/35ce224d68603b4c186e436d20c6cc4f04d27205)
- api 노션 보고 꼼꼼히 봐주십쇼^^^^^^^^^^
- 데이터  확인까지 완료했습니다
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: feat/userApi 생성완료

---

src/components/commons/button.tsx

[feat:common-button 생성했습니다](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/ef1164f21344a2c22a8d73d4bb795e9acfdb1626)
- tiny 사이즈랑  xtiny는 myinfo 페이지에서 사용하시면 됩니다. 
- 나머지 사이즈들은 (medium , large, xlarge) 는 메인페이지에서 사용하시면되고, small은 제껍니다 
```tsx
<CustomButton
variant="whiteButton"
size="tiny"
shape="roundedSquare"
>
프로필 변경
</CustomButton>
```
사용하면 요로케 됩니다~~~
<br/>
<br/>
<br/>
```text
```
3. "Request changes" …

PR: feat/common-button 생성했습니다

---

src/components/commons/input.tsx

- [공용 컴포넌트 input 생성](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/c832fe84537c370bda9bad0718895fd21ca5242d)
- 사용법
```tsx
// signinPage
interface FormValues {
id: string;
password: string;
}
const {
register,
handleSubmit,
formState: {errors},
} = useForm<FormValues>();
<Input
name="id"
placeholder="아이디"
className="w-[200px]"
register={register}
/>
```
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
3. …

PR : feat/common-input

---

src/components/commons/modal.tsx
src/components/commons/overlay.tsx

- [fix : overlay 배경색 제거 및 x 표시 제거](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/a5e371ca5e039de4d9bfc20374186248c74a2a47)
- 불필요한 로직 제거했습니다.
- [feat : Overlay안에서 사용 가능한 Modal 컴포넌트 생성](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/0c83f05bf87f113d2f81e2da43cd43a170aef0ae)
- 사용법
```tsx
<Overlay isOpen={isModalOpen} onClose={() => setIsModalOpen(false)}>
<Modal
title="포획 성공! 확인하러 가기"
buttonText="안간다!"
onClick={() => setIsModalOpen(false)}
secondButtonText="간다!"
onSecondClick={() => setIsModalOpen(false)}
/>
</Overlay>
```
- second는 사용해도되고 안해도 됩니다.
- second 사용 안한 거
- second 사용한 거
<br/>
<br/>
<br/>
<br/>
2. "Review …

PR : feat/common modal

---

package-lock.json
package.json
src/components/commons/input.tsx
src/constants/schema.ts
src/hook/useLogin.ts
src/pages/signinPage.tsx

Resolves: #
[feat: resolver설치했습니다](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/9d0bc72473935a4b9c607f2970e793e0a1649b0a)
- zod schema사용을 위해 설치
[feat: input 에 userid 수정 및 스키마 작성](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/f74f7555e98c01b60793779fd84a7ed30370c924)
- input name을 'userId'로 변경했습니다.
- 간단하게 비밀번호 스키마 작성했습니다.
(아이디, 비밀번호:8글자이상+특수기호1개이상 포함)
[feat:mutation훅 함수 생성 및 로그인로직 생성](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/0bc32b4ef163336281725e2c42c3dc20b162db36)
- useMutation함수 따로 분리해서 작성했습니다.
- 로그인 로직 기능 구현 했습니다.
<br/>
<br/>
3. Comment 입력 …

PR: Feat/signin page

---

src/components/commons/typeButton.tsx

[feat:common-typeButton생성](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/500ef1cf0077c795dcbe35daae3c6f372c31e3d1)
- myInfo페이지에서는 tiny로 설정하시면 됩니다
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR:feat/common-typeButton

---

src/components/commons/pokemonCard.tsx
src/components/commons/typeButton.tsx
src/components/main/encounterPoke.tsx
src/components/myinfo/pokemonBasket.tsx
src/components/myinfo/profileChange.tsx
src/components/myinfo/userInfo.tsx
src/hook/useSignin.ts
src/libs/axios/dataAPI.ts
src/pages/myInfoPage.tsx
src/types/pokeTypes/pokemonData.ts
src/utils/storageUtils.ts
tailwind.config.js

- [feat: 반응형을 위한 screens 사이즈 설정 추가](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/e08805c32f52cd2cbfb4a60b0a63685293370423)
- 반응형을 위한 여러 layout 사이즈를 추가했습니다.
- [feat: myInfoPage 로직 분리 및 pokemonBasket 생성](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/a825bafd9adcf80c0982805ea67fd2b4dc8c7192)
- 기존 myinfoPage의 로직을 분리했습니다.
- pokemonBasket 컴포넌트를 생성했습니다.
- 포획한 포켓몬을 볼 수 있습니다.
- [refactor: 데이터 30개 제한으로 페이지 네이션 없이 한번에 불러오기 위해 로직 변경](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/94ea332be1ed5758857a00a141dea3813bdc4df9)
- 페이지 네이션을 사용하지 않고 한 번에 데이터를 불러오기 위해 getData 로직을 수정했습니다.
- [refactor: pokemoCard에 typeButton으로 type설정](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/2a0d45cc1284a08049121f989e4d98856dc99c84)
- type에 typeButton이 추가되었습니다. …

PR : feat/myinfo page

---

src/components/signin/signinForm.tsx
src/components/signup/signupForm.tsx
src/constants/schema.ts
src/hook/useSignin.ts
src/hook/useSignup.ts
src/libs/axios/userAPI.ts

- [refactor : sign 오타 수정 및 불필요한 로직 삭제 및 modal 추가](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/24be2a1fc5aad892bf46abd620fbe3829e44a4f7)
- 기존 alert를 modal이 보여지도록 변경하였습니다.
- 불필요한 로직을 삭제했습니다.
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: refactor/sign 오타 수정 및 불필요한 로직 삭제 및 modal 추가

---

src/components/myinfo/logoutButton.tsx
src/components/myinfo/userInfo.tsx
src/libs/axios/userAPI.ts
src/pages/myInfoPage.tsx

- [refactor : react-query 데이터 유지 로직 추가](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/8741202c4d1c6d2d57f2e5f2a88feae85b3a9240)
- refetchOnWindowFocus: false,
- staleTime: Infinity,
- cacheTime: 1000 * 60 * 5,
- 를 추가했습니다
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR : refactor/pokebasket

---

src/components/commons/pokemonCard.tsx
src/components/myinfo/pokemonBasket.tsx
src/components/pokemonDetailPage/pokeEvolution.tsx
src/components/pokemonDetailPage/pokeInfo.tsx
src/hook/useCatchPokemon.ts
src/hook/useGetPokeDetail.ts
src/pages/poketMonDetailPage.tsx
src/types/pokeTypes/pokemonData.ts
src/types/pokeTypes/pokemonType.ts

[](feat:detailpage)[feat:detailpage](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/638de50f5218653dd84fa0afcb9594c4bed2e8f4)
- 디테일 페이지 완성했습니다
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: feat/detailpage

---

src/hook/useRandomPokeData.ts
src/libs/axios/pokeAPI.ts

- [refactor: 포켓몬 종류 추가 250->600마리](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/8fb65c456eea24f63e373a33c8736b6f3aa338a8)
- 포켓몬의 종류를 250 -> 600 마리로 증가했습니다
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR : refactor/pokeApi 포켓몬 종류 추가 250->600마리

---

src/components/myinfo/pokemonBasket.tsx
src/components/pokemonDetailPage/pokeInfo.tsx
src/libs/tailwindCss/designToken/color.ts
src/pages/poketMonDetailPage.tsx

resolves: #59 
[refactor : pokemonDetailPage 수정](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/084a56c6d678eb6bde7f5e9214d7771ad4fb4090)
- 디테일 페이지 오버레이로 수정했습니다.
- 디테일 페이지 속 포켓몬 배경과 타입 토글을 해당 타입에 맞는 색으로 바뀌게끔 수정했습니다.
겁나 귀엽쥬?
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: refactor / pokemonDetailPage 수정

---

src/libs/router/router.tsx
src/pages/poketMonDetailPage.tsx

<br/>
<br/>
[fix: error수정](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/2837c7a7a00a4de5319041301146e5373be5af34)
- 라우터에 생긴 error 수정했습니다 
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: fix/ pokeDetailPage error수정

---

src/components/commons/modal.tsx
src/components/myinfo/pokeReleaseButton.tsx
src/components/myinfo/pokemonBasket.tsx
src/libs/axios/dataAPI.ts
src/types/pokeTypes/pokemonData.ts

- [feat/refactor : 놓아주기 버튼 추가](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/708ae1fc5086398e7deff8c8b58a26a8e991a3a5)
- 놓아주기 버튼을 추가했습니다
resolves : #67 
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR : feat/drop poke

---

src/components/commons/input.tsx
src/components/myinfo/logoutButton.tsx
src/components/myinfo/userInfo.tsx
src/components/signup/signupForm.tsx
src/constants/schema.ts
src/hook/useSignup.ts
src/libs/axios/dataAPI.ts
src/libs/axios/userAPI.ts

- [refactor : 회원가입에 닉네임 추가](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/9a54a8afaf30a04aa83506232ff48647166d0d3a)
- 기존에 삭제했던 회원가입에 닉네임을 다시 추가했습니다.
- [refactor: 로그아웃 추가](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/bbb6a7c7380076029dba692d13be4a0baa6fc6f9)
- 로그아웃이 정상적으로 작동하게 수정했습니다
- 로그아웃 시 로그인 페이지로 이동됩니다
- [refactor : nickname 수정 및 추가](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/f8e29b57c4d0ef1017cadf12994811e6d0e98877)
- 닉네임 수정이 정상적으로 작동하게 수정되었습니다
- 수정 버튼 클릭 시 input 창으로 변경됩니다
resolves: #53 
<br/>
<br/>
<br/>
<br/>
3. Comment 입력 (**\*Optional**) 후, …

PR : feat/user info1-1

---

src/components/signin/signinScreen.tsx

- [refactor : signin page button 추가](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/a5afef69b8f285af0ee1141154cd2344bcdb63d8)
- signin page에서 하단을 클릭 해도 동작하게 만들었습니다
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR : refactor/signin page button 추가

---

src/components/myinfo/pokemonBasket.tsx
src/components/myinfo/profileChange.tsx
src/components/myinfo/userInfo.tsx
src/components/signin/signinScreen.tsx
src/hook/useProfileUpdate.ts
src/hook/useSignin.ts
src/libs/axios/userAPI.ts
src/pages/myInfoPage.tsx
src/utils/storageUtils.ts

- [feat : userProfile 생성](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/343591f7fb82df6c7969db86b24a034a4e66fe85)
- 이미지 변경이 가능해졌습니다 !! 체신기술!
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: feat/user profile1-1

---

src/components/layouts/header.tsx
src/components/main/encounterPokeScreen.tsx
src/components/main/mainBackground.tsx
src/components/main/startPoke.tsx

- [refactor : 반응형 설정](https://github.com/mobi-projects/mobi-3rd-2-typescript/commit/9be24ffb3db470c45af11e2474e9ff4b4d0ce23e)
- 해상도에 따라 크기가 달라집니다
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR : refactor/design 반응형 설정

---

src/components/myinfo/userInfo.tsx
src/hook/useUpdateUser.ts

- [refactor: nick name update 로직 분리](https://github.com/mobi-projects/catch-poket-mon/commit/e798cb4a492e3c650010066655d9aa2daa023c4f)
- 기존에 있던 mutate를 커스텀 훅으로 분리했습니다
<br/>
<br/>
<br/>
<br/>
<br/>
```text
```
<br/>
<br/>

PR: refactor/nick name update 로직 분리
